# Generated by Django 4.2 on 2023-07-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="document",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="product",
            name="options",
            field=models.JSONField(null=True),
        ),
    ]
