# Generated by Django 4.2 on 2023-07-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_models", "0002_product_document_product_image_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Created"), ("DEACTIVATED", "Deactivated"), ("ACTIVE", "Active")],
                default="CREATED",
                max_length=255,
            ),
        ),
    ]
