# Generated by Django 4.2 on 2023-07-04 11:23

import apps.sandbox_models.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_models", "0003_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="document",
            field=models.FileField(null=True, upload_to=apps.sandbox_models.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to=apps.sandbox_models.models.get_upload_to),
        ),
    ]
