# Generated by Django 4.2 on 2023-07-04 12:26

import apps.sandbox_models.models
import datetime
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_models", "0004_alter_product_document_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="float_index",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ip_address",
            field=models.GenericIPAddressField(default="127.0.0.1", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="new_product",
            field=models.DurationField(default=datetime.timedelta(days=1), null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=10, default=10, max_digits=100),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="url_field",
            field=models.URLField(default="http://localhost/", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="uuid_field",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="document",
            field=models.FileField(
                null=True,
                upload_to=apps.sandbox_models.models.get_upload_to,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["scv"])],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=apps.sandbox_models.models.get_upload_to,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
            ),
        ),
    ]
