# Generated by Django 4.2 on 2023-07-04 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_models", "0006_product_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="file_path",
        ),
    ]
