# Generated by Django 4.2 on 2023-07-04 15:37

import apps.sandbox_models.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox_models", "0007_remove_product_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="document",
            field=models.FileField(
                null=True,
                upload_to=apps.sandbox_models.models.get_upload_to,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[".scv"])],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=apps.sandbox_models.models.get_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=[".jpg", ".jpeg", ".png"])
                ],
            ),
        ),
    ]
